---
title: "04_descriptive_stats"
author: "Flora"
date: "2022-08-25"
output: html_document
---

# loading packages
```{r}
options(scipen = 999)

suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(sjPlot))
suppressPackageStartupMessages(library(lme4))
suppressPackageStartupMessages(library(psych))
suppressPackageStartupMessages(library(readxl))
```


# importing and joining datasets of self-reports and behavioural assessments
```{r}
dat_pre <- read_xlsx("data/dat_pre.xlsx")
dat_esm <- read_csv("data/data_processed.csv")
dat_unfiltered <- read_csv("data/data_cleaned.csv")
```

# filtering datasets
```{r}
dat_pre_clean <- dat_pre %>% 
  select(session, ended, age, gender, edu) %>% 
  filter(!is.na(ended), age != "under_18") %>% 
  mutate(age = as.numeric(age))
```

# sample demographics

## cross-sectional sample
```{r}

# number and age of participants  
dat_pre_clean %>% 
  select(session, age) %>% 
  summarise(N         = n(),
            Mean      = round(mean(age), digits = 2),
            Median    = round(median(age), digits = 2),
            SD        = round(sd(age), digits = 2),
            Range_min = min(age),
            Range_max = max(age))

# gender
dat_pre_clean %>% 
  select(gender) %>% 
  table()
  
dat_pre_clean %>%
  select(gender) %>% 
  table() %>% 
  prop.table() %>% `*`(100) %>% round(2)
  
  # 1 = Female
  # 2 = Male
  # 3 = Other
  

# education
dat_pre_clean %>% 
  select(edu) %>% 
  table()
  
dat_pre_clean %>% 
  select(edu) %>% 
  table() %>% 
  prop.table() %>% `*`(100) %>% round(2)

  # 1 = Primary school or lower
  # 3 = Vocational school without high school diploma
  # 4 = High school diploma or equivalent 
  # 5 = Bachelor's or Master's degree
  # 6 = Doctorate (PhD)
  # 7 = Other
```


## proceeded to ESM phase = final sample
```{r}

# number and age of participants  
dat_esm %>%
    select(id, age) %>%
    distinct() %>%
    summarise(N         = n(),
              Mean      = round(mean(age), digits = 2),
              Median    = round(median(age), digits = 2),
              SD        = round(sd(age), digits = 2),
              Range_min = min(age),
              Range_max = max(age))


# gender
dat_esm %>% 
  select(id, gender) %>%
  distinct() %>% 
  select(gender) %>% 
  table()

dat_esm %>% 
  select(id, gender) %>%
  distinct() %>% 
  select(gender) %>% 
  table() %>% 
  prop.table() %>% `*`(100) %>% round(2)

  # 1 = Female
  # 2 = Male
  # 3 = Other

  
# education
dat_esm %>% 
  select(id, edu) %>%
  distinct() %>% 
  select(edu) %>% 
  table()

dat_esm %>% 
  select(id, edu) %>%
  distinct() %>% 
  select(edu) %>% 
  table() %>% 
  prop.table() %>% `*`(100) %>% round(2)
  
  # 1 = Primary school or lower
  # 3 = Vocational school without high school diploma
  # 4 = High school diploma or equivalent 
  # 5 = Bachelor's or Master's degree
  # 6 = Doctorate (PhD)
  # 7 = Other
```


# descriptives

## descriptives of ESM surveys in final sample
```{r}

# total number of completed esm surveys
dat_esm %>%
  distinct() %>% 
  summarise(n_id  = length(unique(id)),
            n_obs = length(sad))


#...and per capita
dat_esm %>%
  distinct() %>% 
  group_by(id) %>% 
  summarise(n_obs = length(date_emotics)) %>% 
  ungroup() %>% 
  summarise(max_n_obs    = max(n_obs),
            min_n_obs    = min(n_obs),
            mean_n_obs   = mean(n_obs),
            median_n_obs = median(n_obs),
            sd_n_obs     = sd(n_obs))


# descriptives of negative affect
dat_esm %>%
  select(id, day, beep, negaff) %>%
  summarise(
    mean_negaff   = mean(negaff),
    median_negaff = median(negaff)
  )


# descriptives of event pleasantness
dat_esm %>% 
  select(id, day, beep, event_unpleasantness) %>% 
  summarise(
    mean_evunpleasant   = mean(event_unpleasantness),
    median_evunpleasant = median(event_unpleasantness),
    sd_evunpleasant     = sd(event_unpleasantness),
    min_evunpleasant    = min(event_unpleasantness),
    max_evunpleasant    = max(event_unpleasantness)
  )
```


# calculating compliance in final sample

## compliance on ESM surveys
```{r}

# identify day of quitting
dat_maxday_esm <- dat_cleaned %>% 
  select(id_emo, date_emotics, day) %>% 
  filter(!is.na(date_emotics)) %>% 
  group_by(id_emo) %>% 
  summarise(max_day_esm = max(day))

dat_cleaned <- dat_cleaned %>% 
  left_join(dat_maxday_esm, by = "id_emo")


# calculating compliance
dat_cleaned %>%
  distinct() %>% 
  select(id_emo, date_emotics, day, beep, max_day_esm) %>%
  group_by(id_emo) %>%
  summarise(completed = sum(!is.na(date_emotics)),
            all = max_day_esm * 8, 
            esm_compl_final = (completed / all) * 100
  ) %>%
  ungroup() %>%
  summarise(median_final_compl = median(esm_compl_final, na.rm = T),
            mean_final_compl   = mean(esm_compl_final, na.rm = T),
            sd_final_compl     = sd(esm_compl_final, na.rm = T),
            min_final_compl    = min(esm_compl_final, na.rm = T),
            max_final_compl    = max(esm_compl_final, na.rm = T)
  )
```

