---
title: "04_visualization"
author: "Flora"
output: html_document
---

# loading packages
```{r}
suppressPackageStartupMessages(library(tidyverse))
suppressPackageStartupMessages(library(patchwork))

options(scipen = 999)
```


# reading dataset
```{r message=FALSE}
dat_model <- read_csv("data/data_model.csv")
```


# visualization of all three rumination measures
```{r fig.height=4, fig.width=11}
# state rumination
state_rumi_plot <- dat_model %>% 
  ggplot(aes(x = rumination_centered, y = NA_sum)) +
  geom_jitter(color = "black", alpha = 0.05, size = 2) +
  geom_smooth(method = "lm",
              size = 2.5,
              color = "#219C19") +
   labs(x     = "State rumination",
        y     = "Negative affect",
        title = "A") +
  theme_classic() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 10))

# mean state rumination
mean_state_rumi_plot <- dat_model %>% 
  ggplot(aes(x = mean_state_rumi_grand_centered, y = NA_sum)) +
  geom_jitter(color = "black", alpha = 0.05, size = 2) +
  geom_smooth(method = "lm",
              size = 2.5,
              color = "#FF9500") +
   labs(x     = "Mean state rumination",
        y     = "",
        title = "B") +
  theme_classic() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 10))


# trait rumination
trait_rumi_plot <- dat_model %>% 
  ggplot(aes(x = trait_rumination, y = NA_sum)) +
  geom_jitter(color = "black", alpha = 0.05, size = 2) +
  geom_smooth(method = "lm",
              size = 2.5,
              color = "#609CCE") +
   labs(x     = "Trait rumination",
        y     = "",
        title = "C") +
  theme_classic() +
  theme(axis.title = element_text(size = 14),
        axis.text = element_text(size = 10))


# multipanel figure
multipanel_figure <- state_rumi_plot + mean_state_rumi_plot + trait_rumi_plot

multipanel_figure
```
